import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import GradientFollowCursor from "@/Components/GradientFollowCursor";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sanchit Bhatnagar | SanchitB23",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className={"scroll-smooth"}>
      <body
        className={cn(
          "bg-slate-900 leading-relaxed text-slate-400 antialiased selection:bg-teal-300 selection:text-teal-900",
        )}
      >
        <div className={inter.className}>
          <GradientFollowCursor />
          <div
            className={
              "mx-auto min-h-screen max-w-screen-xl px-6 py-12 font-sans md:px-12 md:py-20 lg:px-24 lg:py-0"
            }
          >
            {children}
          </div>
        </div>
        <SpeedInsights />
      </body>
    </html>
  );
}
